#!/usr/bin/env bash
# Build the SYNTHETIC thermal mosaic and run the optional thermal step on it.
# NO CAMERA TOOK THESE PICTURES: everything here is generated. See SOURCE.md.
# Runs from any folder, in Git Bash (from PowerShell: run_demo.cmd). Needs no internet.
set -euo pipefail
if [[ -n "${WSL_DISTRO_NAME:-}" ]]; then
    echo "This is WSL's bash (what 'bash' starts in PowerShell); it cannot run the Windows tools." >&2
    echo "From PowerShell run run_demo.cmd instead, or run this script in a Git Bash window." >&2
    exit 1
fi
cd "$(dirname "${BASH_SOURCE[0]}")/../.."   # every path below is relative to Dos_Ojos/
export PYTHONIOENCODING=utf-8

DEMO=public_demo/thermal-synthetic
PY=dosojos_drone/.venv/Scripts/python.exe
# Through Python: Windows Smart App Control blocks the unsigned dosojos-*.exe launchers.
DRONE="$PY -m dosojos_drone --workspace $DEMO/workspace"
FIELDS=dosojos_sms/examples/demo_fields.geojson

# The rasters. Only the field's shape is borrowed; the pictures are made up.
"$PY" $DEMO/make_thermal.py --fields $FIELDS --id PUBLIC-rgv-corn-1 \
    --out $DEMO/data --pattern rows

# The thermal step needs a canopy model to tell leaves from soil; here it is the
# one the generator wrote, in place of the one 'chm' would build from a flight.
mkdir -p $DEMO/workspace/out/DEMO-corn-thermal
cp $DEMO/data/chm.tif $DEMO/workspace/out/DEMO-corn-thermal/chm.tif

# --source synthetic is what puts the SYNTHETIC band on every figure.
$DRONE register DEMO-corn-thermal --field PUBLIC-rgv-corn-1 --date 2025-05-19 --crop corn \
    --force --source "synthetic: thermal mosaic generated by make_thermal.py, no camera took it"

# --water-days stands in for the satellite checkbook, which this folder does not run.
$DRONE thermal DEMO-corn-thermal --thermal $DEMO/data/thermal.tif --water-days 5

echo
echo "Done. The picture is $DEMO/workspace/out/DEMO-corn-thermal/thermal.png"
echo "Remember: SYNTHETIC. No camera took it."
